// <auto-generated />
namespace BoVoyage_Projet3.Migration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModiffeDossierReservation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModiffeDossierReservation));
        
        string IMigrationMetadata.Id
        {
            get { return "201807101002032_ModiffeDossierReservation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
